name: Run Postman Tests with Newman

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman and htmlextra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run "api_collection_and_environment/jsonplaceholder_postman_collection.json" \
            --environment "api_collection_and_environment/jsonplaceholder_env.json" \
            --iteration-data "collection_runner/collectionRunnerVariables.csv" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export "newman-reports/htmlextra-report.html"

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-reports/htmlextra-report.html
